// Auto-generated by scaffold-agent — do not edit manually
// Re-generate with: just deploy

const deployedContracts = {
  "31337": {
    "AgentWallet": {
      "address": "0x7872a2a2ddaa79a6d8c7d38ee8a7be47f32b9fb9",
      "abi": [
        {
          "type": "constructor",
          "inputs": [
            {
              "name": "_agent",
              "type": "address",
              "internalType": "address"
            }
          ],
          "stateMutability": "nonpayable"
        },
        {
          "type": "receive",
          "stateMutability": "payable"
        },
        {
          "type": "function",
          "name": "agent",
          "inputs": [],
          "outputs": [
            {
              "name": "",
              "type": "address",
              "internalType": "address"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "execute",
          "inputs": [
            {
              "name": "target",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "value",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "data",
              "type": "bytes",
              "internalType": "bytes"
            }
          ],
          "outputs": [
            {
              "name": "",
              "type": "bytes",
              "internalType": "bytes"
            }
          ],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "owner",
          "inputs": [],
          "outputs": [
            {
              "name": "",
              "type": "address",
              "internalType": "address"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "event",
          "name": "Executed",
          "inputs": [
            {
              "name": "target",
              "type": "address",
              "indexed": true,
              "internalType": "address"
            },
            {
              "name": "value",
              "type": "uint256",
              "indexed": false,
              "internalType": "uint256"
            },
            {
              "name": "data",
              "type": "bytes",
              "indexed": false,
              "internalType": "bytes"
            }
          ],
          "anonymous": false
        }
      ]
    }
  }
} as const;

export default deployedContracts;
